apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- dashboard-ingress.yaml
patchesStrategicMerge:
- configmap-feature-flags-patch.yaml
namespace: tekton-pipelines
